<%@ page language="java" contentType="text/html" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="jax" tagdir="/WEB-INF/tags" %>
<jax:mmhcpage title="About Us">

	<jsp:body>	
		<section class="container content">
			

                    <p>
                        The Mouse Models of Human Cancer database (MMHCdb) is an expertly curated compendium of in vivo mouse models of human cancer. 
                        To ensure maximum data accessibility and compatibility we follow strict adherence to community nomenclature standards, ontologies, and minimal information standards. 
                        This work benefits cancer researchers by making it easier to aggregate information from the same or related mouse models. 
                        It is fundamental to making mouse models of human cancer and their associated data Findable, Accessible, Interoperable, and Reusable (FAIR). 
                        We also facilitate the informed selection and use of mouse models by highlighting the impact that genetic background has on key cancer characteristics, 
                        including cancer susceptibility, the spectrum of tumor types and frequencies observed in a model, age of tumor onset/detection, and metastatic potential.

                    </p>
                    <p>
                        See the <a href="https://en.wikipedia.org/wiki/Mouse_Models_of_Human_Cancer_database" target="_blank">MMHCdb Wikipedia page</a>.  
                    </p>
                    <p>
                        MMHCdb has partnered with the European Bioinformatics Institute to develop <a href="https://www.pdxfinder.org">PDX Finder</a>, a global catalog of Patient Derived Xenograft models.
                    </p>
			

			<h3>Content (Updated July 2020) </h3>


                                <table class="fig">
                                    <tr><td data-tip="Mouse model: Defined as a group of tumor frequency records that share a unique combination of Tumor, Strain, and Treatment(s). ">MMHCdb: Mouse Models</td><td style="text-align:left">57,692</td></tr>
                                    <tr><td data-tip="Tumor frequency records: Defined as a unique observation of a Tumor,  Strain, and Treatment(s) with attributes (when available) for age of detection, age of onset, strain sex, colony size, number of affected mice, and treatment details.">MMHCdb: Tumor Frequency Records</td><td style="text-align:left">106,500</td></tr>
                                    <tr><td data-tip="References: Data in MMHCdb are associated with information about the source of the data. The majority of sources are peer-reviewed publications.">MMHCdb: References</td><td style="text-align:left">19,242</td></tr>
                                    <tr><td data-tip="Histopathology images: Histology (H&E) an/or immunohistochemistry (IHC) images associated with specific tumor frequency records. Images are displayed with permission of published and/or submitting author.">MMHCdb: Histopathology Images</td><td style="text-align:left">6,594</td></tr>
                                    <tr><td data-tip="PDX models: Patient Derived Xenograft models are generated by engrafting fragments from human tumors in immunodeficient or humanized mouse hosts. ">PDX Finder: PDX models</td><td style="text-align:left">4,031</td></tr>
                                </table>


                                    <h3>The MMHCdb team:</h3>
                                    <p>Debra M. Krupke, MS, Senior Biocuration Scientist
                                    <br>Dale A. Begley, PhD, Senior Biocuration Scientist
                                    <br>Steven B. Neuhauser, BA, Scientific Software Engineer
                                    <br>John P. Sundberg, DVM, PhD, Professor, co-Investigator
                                    <br>Carol J. Bult, PhD, Professor and Knowlton Family Chair, Principal Investigator</p>

                                    <h3>Funding</h3>
                                    <p>MMHCdb is supported by NCI grant <a href="https://projectreporter.nih.gov/project_info_description.cfm?aid=9264508&icde=37130427" target=blank>CA089713</a>.</p>
                                    <h3>Citing the Resource</h3>
                                    <p>Learn how to cite this resource <a href="${pageContext.request.contextPath}/citation.jsp">here</a></p>


		</section>
	</jsp:body>
	
</jax:mmhcpage>
